### ISSUE TITLE
[Plank Sack] Filling sack at bank, counter desync

### ISSUE THREAD

**Issue by AnonP2X3YZ** [Enriath/external-plugins#58]
This issue is for the external plugin: {Plank Sack}

Similar to a previously closed issue addressing Plank Sack de-sync, previous submitter stated: 
    _"I think some other actions also create a similar de-sync when, but couldn't pinpoint the which ones"_

To replicate:
-After 2-3 Mahogany homes
-Go back to the bank with 5-12 planks left in the plank sack
-Take out a new inventory filled with planks
-Click to fill the plank sack 
-I typically have around ~25ish in the plank sack after initial fill, so I take out another inventory full of planks
-Click to fill the plank sack again, and instead of going to 28, it sometimes goes to 27, even though the plank sack is full
-OR instead of going to 27, it goes to 28
-Right click "check plank sack", chat will say 27/28, and then the plank sack will update to 27/28. 

During this banking process, I'm not experiencing any lag, ~35ms, 650ms p/tick with no spikes in the graph. This issue happens nearly really often when I go to bank and fill the plank sack (~50% of the time). 

Here is a video of the bug in action: https://www.youtube.com/watch?v=dgZw4hJ6Pes

**Comment by Hydrox6** [comment]
This doesn't say anything useful, and there's no proof here that the desync even happens with the bank, as you didn't confirm the amount of planks already in the sack before.

**Comment by AnonP2X3YZ** [comment]
> This doesn't say anything useful, and there's no proof here that the desync even happens with the bank, as you didn't confirm the amount of planks already in the sack before.

The reason I didn't confirm the amount of the planks in the sack before was because then if it was incorrect, it would correct it automatically, defeating the purpose of showing the bug on video. To be honest, I'm not sure what causes it 100%, I was just trying to show the bug and how it happens to me. 

I was able to get my construction level to where I want it today (82), and don't plan to train it again, so its not a huge deal to me anymore. Regardless, the plugin was very helpful nonetheless, even with the slight desync which resulted in some awkward banking / run estimating. Thank you.

**Comment by Hydrox6** [comment]
> The reason I didn't confirm the amount of the planks in the sack before was because then if it was incorrect, it would correct it automatically, defeating the purpose of showing the bug on video.

If that had happened, then you would have proved that the desync wasn't at the bank. What you submitted instead doesn't say anything at all about the issue, only that you noticed it at that point; as I said before, it doesn't say anything useful.

**Comment by Enriath** [comment]
The likely cause of this desync has been fixed (#100)

**Comment by ZachNich** [comment]
Can confirm a desync is still happening on v1.3.1. Replicable when interacting with a bank. To replicate: Withdraw planks from bank, exit bank interface, fill plank sack within the same tick or two.
